// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AgreeCheckboxController from "./agree_checkbox_controller"
application.register("agree-checkbox", AgreeCheckboxController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IntroController from "./intro_controller"
application.register("intro", IntroController)

import UserSymptomsController from "./user_symptoms_controller"
application.register("user-symptoms", UserSymptomsController)

import VideoBackgroundController from "./video_background_controller"
application.register("video-background", VideoBackgroundController)
